apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform/vault/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
