apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform-runner
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./terraform/runner
  dependsOn:
    - name: vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform-vault
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./terraform/vault/terraform
  dependsOn:
    - name: terraform-runner
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
