apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
